#!/bin/bash
clear
red='\e[1;31m'
green='\e[1;32m'
blue='\e[0;34m'
purple='\e[1;35m'
blue_b='\e[0;94m'
NC='\e[0m'
echo -e "\e[0m                                                                              "                                                                                                           
echo -e "\e[93m                           AutoScript MZTECH-VPN                             "                                                                            
echo -e "\e[1;32m             ________________________________________________              "
echo -e "\e[1;32m           |    _________________________________________    |             "                                         
echo -e "\e[1;32m           |   |  root:                                  |   |             "                                     
echo -e "\e[1;32m           |   |    - Script By MZTECH-VPN               |   |             "
echo -e "\e[1;32m           |   |    - Thanks To Allah SWT                |   |             "
echo -e "\e[1;32m           |   |    - Telegram : t.me/mztechvpn          |   |             "
echo -e "\e[1;32m           |   |    - Thanks for who using this script   |   |             "
echo -e "\e[1;32m           |   |    - To EnterMenuList = 'menu'          |   |             "                                                    
echo -e "\e[1;32m           |   |    - Tiada Tuhan Melainkan Allah        |   |             "
echo -e "\e[1;32m           |   |_________________________________________|   |             "                                                          
echo -e "\e[1;32m            \_______________________________________________/              "
echo -e "\e[1;32m                   \___________________________________/                   "
echo -e "\e[93m                             COPYRIGHT © 6/2004                              "
echo -e "\e[93m                        MZTECHVPN POWERED BY MZTECH                          "
echo -e "\e[93m               Privacy Policy Terms & Conditions Disclaimer                "                                                                                                
echo -e "\e[93m          .----------------------------------------------------.           "
echo -e "\e[93m          |             Script status : Premium                |           "
echo -e "\e[93m          '----------------------------------------------------'           "
echo -e  ""
echo -e  "${red}TYPE 'menu' TO GO TO MAIN OR 'exit' TO LOGOUT"${NC}
echo -e  ""

